mlcommons/chakra

et_converter/pytorch2chakra_converter.py

- This has been tested with the latest Chakra on an Ubuntu 22.04 machine.
- The traces are from Resnet-50, distributed data parallel, with a Graph Trace Observer.
- This PR adds annotations for handling the traces.  
Chakra
```
python3 -m chakra.et_converter.et_converter --input_type PyTorch --input_filename result/eg.rank_0.pt.trace_plus.json --output_filename et_plus/chakra.0.et --num_dims 1
python3 -m chakra.et_converter.et_converter --input_type PyTorch --input_filename result/eg.rank_1.pt.trace_plus.json --output_filename et_plus/chakra.1.et --num_dims 1
```
Astra-sim
```
./build/astra_analytical/build/bin/AstraSim_Analytical_Congestion_Unaware --workload-configuration=./extern/graph_frontend/chakra/et_plus/chakra --system-configuration=./inputs/system/FullyConnected.json …
```

[chakra][et_converter] Add Annotation for Graph Trace Observer in PyTorch

---

et_visualizer/et_visualizer.py

This pull request introduces a new function `escape_label` in the `et_visualizer` module to escape special characters in labels for Graphviz rendering.
```
$ python3 -m chakra.et_visualizer.et_visualizer --input_filename ~/rank0.chakra --output_filename rank0.pdf
```

et_visualizer: Escape labels for graph rendering

---

et_feeder/et_feeder_node.cpp
et_feeder/et_feeder_node.h
et_visualizer/et_visualizer.py

This pull request updates the `et_feeder` module to fix a critical parsing issue. The problem stemmed from two main sources: inadequate support in protobuf for the `oneof` boolean value, and a bug within the `ETFeederNode::assign_attr_val` function.
```
$ cd ~/param
$ cd param/train/comms/pt
$ cd ../../compute/python
$ pip install -r requirements.txt
$ python setup.py install
$ python tools/trace_link.py --pytorch-et-file ~/llama_pytorch_et/llama_et_0.json --kineto-file ~/llama_kineto/worker0_step_12.1697596714999.pt.trace.json --output-file ~/rank0.json
$ cd ~/charka
$ python3 -m chakra.et_converter.et_converter --input_type PyTorch --input_filename ~/rank0.json --output_filename ~/rank0.chakra --num_dims 1 
$ cp ~/rank0.chakra chakra.0.et && cp …
```

et_feeder: Bugfix in attr parsing in et_feeder

---

et_converter/text2chakra_converter.py

Update text converter to use v0.0.4 schema
```
python -m chakra.et_converter.et_converter \
--input_type Text \
--input_filename ${ASTRASIM_DIR}/inputs/workload/ASTRA-sim-1.0/Resnet50_DataParallel.txt \
--output_filename Resnet50_DataParallel \
--num_dims 1 \
--num_npus 64 \
--num_passes 1
```

et_converter: Support Chakra v0.0.4 in text2chakra converter

---

et_feeder/et_feeder.cpp

This PR introduces a significant improvement in error handling within the ETFeeder::lookupNode method. By catching and handling std::out_of_range exceptions, the update ensures that any attempt to access a non-existent node ID in the dependency graph is met with a clear and informative error message.
```
$ cd ~/param
$ cd param/train/comms/pt
$ cd ../../compute/python
$ pip install -r requirements.txt
$ python setup.py install
$ python tools/trace_link.py --pytorch-et-file ~/llama_pytorch_et/llama_et_0.json --kineto-file ~/llama_kineto/worker0_step_12.1697596714999.pt.trace.json --output-file ~/rank0.json
$ cd ~/charka
$ python3 -m chakra.et_converter.et_converter --input_type PyTorch --input_filename ~/rank0.json --output_filename ~/rank0.chakra --num_dims …
```

Enhance error handling in ETFeeder::lookupNode with detailed exception messages

---

et_converter/pytorch2chakra_converter.py
et_converter/pytorch_node.py
et_converter/pytorch_tensor.py

This pull request significantly refactors the `et_converter` module, with a particular focus on enhancing the PyTorch2Chakra converter:
- Shifted towards an object-oriented approach for improved readability and maintainability.
- Revised the logic for data dependency identification:
- Moved away from using tensor input-output relationships.
- Now follows control dependencies to accurately encode data dependencies.
- Introduced utility functions for:
- Cycle detection to validate dependencies.
- Execution simulation for easier simulation of final Chakra traces.
- Enhanced documentation through detailed logging and comments to explain the conversion process from traces to final Chakra traces, addressing previous bugs and limitations.
```
$ cd ~/param
$ cd param/train/comms/pt
$ pip install …
```

Refactoring PyTorch2Chakra converter for better readability and dependency handling

---

.flake8
.github/workflows/python_lint.yml
.gitignore
.pyre_configuration
et_converter/et_converter.py
et_converter/flexflow2chakra_converter.py
et_converter/pytorch2chakra_converter.py
et_converter/pytorch_node.py
et_converter/pytorch_tensor.py
et_converter/text2chakra_converter.py
et_visualizer/et_visualizer.py
timeline_visualizer/timeline_visualizer.py
utils/et_generator/et_generator.py

* Enabled flake8 and pyre linting.
* Added automated linting workflow.
* Fixed flake8 and pyre warnings/errors.
Ran flake8 and pyre.
```
$ flake8 .
$ pyre check
```
Ran post-processing steps.
```
$ cd ~/param
$ cd param/train/comms/pt
$ cd ../../compute/python
$ pip install -r requirements.txt
$ python setup.py install
$ python tools/trace_link.py --pytorch-et-file ~/llama_pytorch_et/llama_et_0.json --kineto-file ~/llama_kineto/worker0_step_12.1697596714999.pt.trace.json --output-file ~/rank0.json
$ cd ~/charka
$ python3 -m chakra.et_converter.et_converter --input_type PyTorch --input_filename ~/rank0.json --output_filename ~/rank0.chakra --num_dims 1
```

Integrate flake8 and pyre for automated linting and type checking

---

utils/et_jsonizer/et_jsonizer.py

Updated et_jsonizer for readability and maintainability.
```
$ python3 -m chakra.et_jsonizer.et_jsonizer --input_filename ~/rank0.chakra --output_filename ~/rank0.chakra.json
$ tail ~/rank0.chakra.json
{
"name": "is_cpu_op",
"int32Val": 0
},
{
"name": "ts",
"int64Val": "1697596710335517"
}
]
}%               
```

et_jsonizer: Refactor et_jsonizer

---

INSTALL.md
et_converter/et_converter.py
et_converter/pytorch2chakra_converter.py
et_converter/text2chakra_converter.py
et_feeder/et_feeder_node.cpp
et_feeder/et_feeder_node.h
utils/et_generator/et_generator.py

Removed num_dims and involved_dim as they are ASTRA-sim specific.
```
$ python3 -m chakra.et_converter.et_converter --input_type PyTorch --input_filename ~/rank0.json --output_filename ~/rank0.chakra
$ python3 -m chakra.et_converter.et_converter --input_type Text --input_filename ~/astra-sim/inputs/workload/ASTRA-sim-1.0/MLP_ModelParallel.txt --output_filename ~/rank0.chakra --num_npus 1 --num_passes
10
$ python -m chakra.et_generator.et_generator
```

Remove num_dims and involved_dim

---

et_feeder/et_feeder_node.cpp
et_feeder/et_feeder_node.h

Provide an interface for users to read other optional attrs, which is not predefined in ETFeeder.
Should be after PR #8

Changhai etfeeder others attrs

---

et_converter/pytorch2chakra_converter.py
et_converter/pytorch_node.py

- Introduced support for associating multiple GPU child operators with a single CPU operator.
- Added support for Tensor(c10::BFloat16) in get_data_type_size.
- Removed the method for splitting overlapping CPU and GPU operations due to its impact on operator sequencing.
- Observed error rate reduction from 40% to 6% in Megatron traces by eliminating splitting logic.
```
$ python tools/trace_link.py --pytorch-et-file ~/Downloads/megatron_et_0.json --kineto-file ~/Downloads/megatron_kineto_0.json --output-file ~/rank0.json &
$ python tools/trace_link.py --pytorch-et-file ~/Downloads/megatron_et_1.json --kineto-file ~/Downloads/megatron_kineto_1.json --output-file ~/rank1.json &
$ python tools/trace_link.py --pytorch-et-file ~/Downloads/megatron_et_2.json --kineto-file …
```

Support multi-gpu child ops and remove CPU/GPU op splitting

---

.github/workflows/main.yml
pyproject.toml

This PR is intended to  simplify the modules calling. It has the following additions:
- updates the github checkout action to the last version
- offers a solution to that redundancy problem when calling modules. For this, the pyproject.toml file was enhanced and the structure of the project was not modified.
- now the user can call a module like this: 
> chakra_generator --num_npus 1
instead of 
> python3 -m chakra.et_generator.et_generator --num_npus 1
- also, the old syntax is still available
- updates the main.yml workflow example to match the new syntax
Tested locally after installing the package. 
Tested to see if it behaves the same as the previous approach of calling modules.

Modules calling simplified

---

test_trace_link.py
trace_link.py

As per the Chakra forum's consensus, let's move the trace link from param repo to here. 
This commit simply moves these files, we will need to follow up with a diff to integrate them.

Adding trace link files from Params repo to here

---

pyproject.toml

Ignore trace_link.py and test_trace_link.py in ruff
GitHub actions are passing.

Ignore trace_link.py and test_trace_link.py in ruff

---

.pyre_configuration
et_converter/pytorch2chakra_converter.py
et_converter/pytorch_node.py

Fix bugs in et_converter
* Fix formatting due to ruff in et_converter/pytorch2chakra_converter.py
* Remove UniqueIdAssigner from et_converter/pytorch2chakra_converter.py
* Update pytorch2chakra_converter to support various versions
* Ignore et_converter/ for pyre checks
* Use GPU operator's name for identifying communication type
* Fix communication size calculation logic
* Remove inter-stream dependencies
**1. Run trace_link**
```
chakra_trace_link --pytorch-et-file /Users/theo/Downloads/llama_pytorch24.05/megatron_et_0.json --kineto-file /Users/theo/Downloads/llama_pytorch24.05/megatron_kineto_0.json --output-file ~/megatron_0.json &
chakra_trace_link --pytorch-et-file /Users/theo/Downloads/llama_pytorch24.05/megatron_et_1.json --kineto-file …
```

Fix bugs in et_converter

---

.github/workflows/python_lint.yml
pyproject.toml
requirements-dev.txt
src/converter/pytorch_converter.py
src/trace_link/trace_link.py

Enable Pyright for type checking
**1. CI/CD pipelines are passing
2. Correlation**
**2.1 Run trace_link**
```
chakra_trace_link --pytorch-et-file /Users/theo/Downloads/llama_pytorch24.05/megatron_et_0.json --kineto-file /Users/theo/Downloads/llama_pytorch24.05/megatron_kineto_0.json --output-file ~/megatron_0.json &
chakra_trace_link --pytorch-et-file /Users/theo/Downloads/llama_pytorch24.05/megatron_et_1.json --kineto-file /Users/theo/Downloads/llama_pytorch24.05/megatron_kineto_1.json --output-file ~/megatron_1.json &
chakra_trace_link --pytorch-et-file /Users/theo/Downloads/llama_pytorch24.05/megatron_et_2.json --kineto-file /Users/theo/Downloads/llama_pytorch24.05/megatron_kineto_2.json --output-file ~/megatron_2.json &
chakra_trace_link --pytorch-et-file …
```

Enable Pyright for Type Checking

---

src/feeder/et_feeder_node.cpp
src/feeder/et_feeder_node.h

This PR fixes the `is_cpu_op()` method which was always returning `false`, due to a `wrong conversion` in the constructor.
- the `is_cpu_op()` method is returning `bool`, but variable `is_cpu_op_` was of type `uint32_t` --> changed it to `bool`
- the conversion in the constructor of `ETFeederNode` was being done in `uint32_t` instead of `bool` --> changed it to `bool`
- in trace, the value for `is_cpu_op` attribute is a `bool`
I've tested using `2 different traces`, converted them to `json` using `chakra_jsonizer` and checked if the `value returned by is_cpu_op()` method for a specific node is `the same with the one from the json`.

fixes is_cpu_op conversion in constructor

---

.github/workflows/codeql.yml
src/feeder/et_feeder.cpp
src/feeder/et_feeder.h
src/feeder/et_feeder_node.cpp
src/feeder/et_feeder_node.h

This PR adds a workflow which enables Github Code Scanning (the engine used is CodeQL).
It provides a suite of security queries that are run on every push and pull request on main branch. The results are visible in the security tab. This also represents a check in a PR context.
The scan is being done on python and C++ code (the C++ code needs a build step; I've built et_feeder as shared lib).
Example (the errors also appear as comments in the PR):
The testing was done by adding known bad lines of code to see if the problems are identified. An example could be seen in the picture above.

Adds Github Code Scanning (CodeQL) 

---

src/trace_link/kineto_operator.py
src/trace_link/trace_linker.py
src/trace_link/unique_id_assigner.py
tests/trace_link/test_kineto_operator.py

Refactor trace_link.
- Updated the maximum column length to 120.
- Improved the documentation in docstrings.
- Renamed functions to improve readability (construct_kineto_data_structures, is_cpu_op, is_gpu_op, is_cuda_launch_op).
- Added missing type annotations.
```
$ pip install . 
Processing /Users/theo/chakra-official
Requirement already satisfied: networkx in …
```

Refactor trace_link

---

src/trace_link/trace_linker.py

Print detailed error message on exception in get_start_timestamp_for_gpu_op
**Previous Version**
```
Traceback (most recent call last):                                                                                                                                                                                                     
File "/Users/theo/venv/bin/chakra_trace_link", line 8, in <module>                                                                                                                                                                   
sys.exit(main())                                                                                                                                                                                                                   
File …
```

Print detailed error message on exception in get_start_timestamp_for_gpu_op

---

src/trace_link/trace_linker.py

Remove `get_start_timestamp_for_gpu_op` from `trace_linker.py`. In `find_parent_cpu_op`, the timestamp of a GPU operator must be determined to identify the correct parent CPU operator. The timestamp of a GPU operator is actually determined by the CUDA launcher operator that launched the GPU operator. To determine the timestamp of a GPU operator, we previously used `get_start_timestamp_for_gpu_op`. However, it turns out that this function is not actually required and buggy. This PR removes `get_start_timestamp_for_gpu_op`. The bug was due to the limitation of external IDs. Previously, we used external IDs for matching a GPU operator with a CPU operator. However, it is not guaranteed that external IDs always match. Instead, the correlation field appears to be a better way to correlate a GPU …

Remove get_start_timestamp_for_gpu_op from trace_linker.py

---

src/trace_link/trace_linker.py
tests/trace_link/test_trace_linker.py

Add unit tests for TraceLinker methods
```
$ python3 ci_tools/integration_tests.py --tgz_path tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05.tgz --num_ranks 8 --tolerance 0.05 --expected_times_ms 14597 14597 14968 14638 14649 14700 14677 14735
Running command: chakra_trace_link --pytorch-et-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_host_et_0.json --kineto-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/kineto_0.json --output-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_et_plus_0.json
Running command: chakra_trace_link --pytorch-et-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_host_et_1.json --kineto-file …
```

Add unit tests for TraceLinker methods

---

tests/jsonizer/test_jsonizer.py

Add unit tests for jsonizer
CI pipelines pass.

Add unit tests for jsonizer

---

src/converter/pytorch_converter.py

Refactored pytorch_converter.py to enhance testability
```
Requirement already satisfied: pyparsing>=3 in …
```

Refactored pytorch_converter.py to enhance testability

---

src/converter/pytorch_node.py

Update docstring to comply with coding style and max column length
CI pipelines pass

Update docstring to comply with coding style and max column length

---

src/trace_link/trace_linker.py
tests/trace_link/test_trace_linker.py

Refactor `TraceLinker` methods to avoid direct member variable updates for better testability
```
$ pip install .             
Requirement already satisfied: pydot in /Users/theo/venv/lib/python3.10/site-packages (from chakra==0.0.4) …
```

Refactor `TraceLinker` methods to avoid direct member variable updates for better testability

---

src/converter/pytorch_converter.py

Refactor PyTorchConverter to accept arguments for improved testability
```
$ python3 ci_tools/integration_tests.py --tgz_path tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05.tgz --num_ranks 8 --tolerance 0.05 --expected_times_ms 14597 14597 14968 14638 14649 14700 14677 14735
Running command: chakra_trace_link --pytorch-et-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_host_et_0.json --kineto-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/kineto_0.json --output-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_et_plus_0.json
Running command: chakra_trace_link --pytorch-et-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_host_et_1.json --kineto-file …
```

Refactor `PyTorchConverter` to accept arguments for improved testability

---

tests/trace_link/test_trace_linker.py

- This PR depends on https://github.com/mlcommons/chakra/pull/85
- Add tests for TraceLinker methods to improve coverage
```
$ pip install .             
Requirement already satisfied: pydot in …
```

Add tests for TraceLinker methods to improve coverage

---

tests/converter/test_pytorch_converter.py
tests/converter/test_pytorch_node.py

* This PR depends on https://github.com/mlcommons/chakra/pull/87
* Add tests for PyTorchConverter
```
$ python3 ci_tools/integration_tests.py --tgz_path tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05.tgz --num_ranks 8 --tolerance 0.05 --expected_times_ms 14597 14597 14968 14638 14649 14700 14677 14735
Running command: chakra_trace_link --pytorch-et-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_host_et_0.json --kineto-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/kineto_0.json --output-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_et_plus_0.json
Running command: chakra_trace_link --pytorch-et-file …
```

Add tests for PyTorchConverter

---

src/visualizer/visualizer.py

Add docstrings and enhance help messages in visualizer
```
$ chakra_visualizer --help
usage: chakra_visualizer [-h] --input_filename INPUT_FILENAME --output_filename OUTPUT_FILENAME
Execution Trace Visualizer
options:
-h, --help            show this help message and exit
--input_filename INPUT_FILENAME
Input Chakra execution trace filename
--output_filename OUTPUT_FILENAME
Output graph filename. Supported extensions are pdf, dot, and graphml. Recommend
using graphml for large graphs for rendering speed.
```
```
$ chakra_visualizer --input_filename megatron_0.chakra --output_filename megatron_0.graphml 
$ head megatron_0.graphml 
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" …
```

Add docstrings and enhance help messages in visualizer

---

requirements-dev.txt
src/visualizer/visualizer.py

Update ruff version to 0.3.7 in requirements-dev.txt
1. CI pipelines pass
2. Ran trace_link & converter
```
$ python3 ci_tools/integration_tests.py --tgz_path tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05.tgz --num_ranks 8 --tolerance 0.05 --expected_times_ms 14597 14597 14968 14638 14649 14700 14677 14735
Running command: chakra_trace_link --pytorch-et-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_host_et_0.json --kineto-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/kineto_0.json --output-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_et_plus_0.json
Running command: chakra_trace_link --pytorch-et-file …
```

Update ruff version to 0.3.7 in requirements-dev.txt

---

pyproject.toml
setup.py
src/converter/converter.py
src/converter/pytorch_converter.py
src/converter/pytorch_node.py
src/converter/pytorch_tensor.py
src/generator/generator.py
src/jsonizer/jsonizer.py
src/timeline_visualizer/timeline_visualizer.py
src/trace_link/kineto_operator.py
src/trace_link/trace_link.py
src/trace_link/trace_linker.py
src/trace_link/unique_id_assigner.py
src/visualizer/visualizer.py

* This PR depends on https://github.com/mlcommons/chakra/pull/89
* Improve maintainability and PEP 8 compliance for Chakra trace generator
```
Requirement already satisfied: pydot in …
```

Improve maintainability and PEP 8 compliance for Chakra trace generator

---

src/generator/generator.py

Add methods to generate various trace nodes in generator
```
Requirement already satisfied: pyparsing>=3 in …
```

Add methods to generate various trace nodes in generator

---

src/trace_link/trace_link.py
src/trace_link/trace_linker.py
tests/trace_link/test_trace_linker.py

Refactor TraceLinker for improved testability 
```
$ pip install .   
py  Installing build dependencies ... -th\|3done
Requirement already satisfied: pyparsing>=3 …
```

 Refactor TraceLinker for improved testability 

---

src/trace_link/trace_linker.py

Remove unused pytorch_et_plus_data from TraceLinker class
**1. CI pipelines pass.
2. Simulated traces**
``` …
```

Remove unused pytorch_et_plus_data from TraceLinker class

---

src/converter/pytorch_converter.py

Ignore Optimizer.step nodes covering >90% runtime, plan to generalize later
[traces.zip](https://github.com/user-attachments/files/15972511/traces.zip)
```
$ python3 ci_tools/integration_tests.py --tgz_path tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05.tgz --num_ranks 8 --tolerance 0.05 --expected_times_ms 14597 14597 14968 14638 14649 14700 14677 14735                                                                    
Running command: chakra_trace_link --pytorch-et-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/chakra_host_et_0.json --kineto-file tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05/kineto_0.json --output-file …
```

Ignore Optimizer.step nodes covering >90% runtime, plan to generalize later

---

src/converter/pytorch_node.py
tests/converter/test_pytorch_node.py

Support Charka schema 1.1.0-chakra.0.0.4
```
Requirement already satisfied: pyparsing>=3 in /Users/theo/venv/lib/python3.10/site-packages (from …
```

Support Charka schema 1.1.0-chakra.0.0.4

---

src/converter/pytorch_converter.py
src/converter/pytorch_node.py
tests/converter/test_pytorch_converter.py

This pull request addresses several bugs in identifying SEND and RECV nodes and calculating communication sizes.
**Changes Made:**
1. **Update PyTorchConverter to Properly Identify SEND and RECV Nodes:**
- Modified the `get_chakra_node_type_from_pytorch_node` method to ensure only GPU operators are identified as communication operators. Previously, CPU nodes like `c10d:send` and `c10d:recv` were incorrectly identified as SEND or RECV nodes.
- Improved the identification of SEND or RECV nodes by using the `ncclDevKernel_SendRecv` keyword and determining the type based on the parent or grandparent node name. If the parent node is `record_param_comms`, the grandparent node name is used; otherwise, the parent node name suffices.
2. **Fix Bug in Encoding Metadata for Communication Nodes:**
- …

Fix identification and metadata encoding for SEND and RECV nodes in PyTorchConverter

---

.github/workflows/end_to_end_tests.yml
.github/workflows/python_tests.yml
USER_GUIDE.md
src/trace_link/kineto_operator.py
src/trace_link/trace_linker.py
tests/trace_link/test_trace_linker.py

Update USER_GUIDE.md and Python imports to use the latest PARAM branch
**1. CI pipelines pass**
**2. Ran the converters**
```
DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Preparing wheel metadata ... done
Requirement already satisfied: protobuf==4.* in /Users/theo/chakra-venv/lib/python3.10/site-packages (from …
```

Update USER_GUIDE.md and Python imports to use the latest PARAM branch

---

src/trace_link/kineto_operator.py
src/trace_link/trace_linker.py
tests/trace_link/test_kineto_operator.py

Add keywords for identifying CUDA runtime operators in the is_cuda_launch_op method (cuLaunchKernel, cuLaunchKernelEx). Idan reported a bug where the output of the trace linker does not generate ncclDevKernel nodes. This issue arose because the CUDA runtime operators were not properly identified, resulting in the loss of the child ncclDevKernel nodes.
When you run the trace linker, you see a lot of messages complaining that GPU operators are dropped
```
...                                                                                                                                                                                                    
[2024-07-01 13:46:31,162] trace_linker.py:767 [WARNING]: No CUDA runtime operator found for correlation ID 29853. …
```

Add keywords for CUDA runtime ops in is_cuda_launch_op method

---

src/converter/pytorch_converter.py

Encode is_cpu_op as a boolean value in the converter. Previously, the converter encoded is_cpu_op as an int32_t, which led to a bug in the parsing logic and the CI pipelines. This PR fixes the bug and correctly encodes is_cpu_op as a boolean value.
1. CI pipeline passes.
2. Confirmed with Idan at NVIDIA

Encode is_cpu_op as a boolean value in the converter

---

src/converter/converter.py
src/converter/pytorch_converter.py
src/converter/text_converter.py
src/trace_link/trace_linker.py
tests/converter/test_pytorch_converter.py
tests/trace_link/test_trace_linker.py

Configure global logging, refactor classes to use direct logging calls
```
$ pip install .             
Requirement already satisfied: pyparsing>=3 in …
```

Configure global logging, refactor classes to use direct logging calls

---

src/converter/converter.py
src/converter/pytorch_converter.py
src/converter/pytorch_node.py

Add stream ID to GPU operators and support multiple streams in simulate_execution. There are two problems in the current main branch. First, the converter does not encode stream ID to GPU operators. Second, the simulate_execution method does not take stream IDs into account, resulting in the serialization of all GPU operators. As a result, for a specific trace, while the measured runtime is 4087.535ms, the simulated runtime with the simulated simulate_execution is 14802.3ms. This PR fixes the issue by encoding stream ID to GPU operators and supporting multi-stream in simulate_execution. Disabled simulate_execution by default because it takes too long now that the converter supports multiple streams.
**1. Correlation 1**
```
$ chakra_trace_link \
--pytorch-et-file …
```

Add stream ID to GPU operators and support multiple streams in simulate_execution

---

src/trace_link/trace_linker.py

Add detailed docstrings to TraceLinker methods and refactor code
This PR only reformats the code without any changes to the interface. It is not needed.

Add detailed docstrings to TraceLinker methods and refactor code

---

src/trace_link/trace_linker.py
tests/trace_link/test_trace_linker.py

Extract get_inter_thread_dep method to simplify link_ops
1. Added unit tests, and CI passes.
2. Correlation
```
Requirement already satisfied: …
```

Extract get_inter_thread_dep method to simplify link_ops

---

.github/workflows/python_lint.yml
pyproject.toml
src/trace_link/trace_linker.py
tests/trace_link/test_trace_linker.py

Remove try-except to ensure trace_link stops on exception. With try-except as shown in the main branch, it catches the exception, prints out the error message, and keeps going even if the variables are not updated properly. It should raise an exception and exit. This PR allows raising an exception and stopping.
1. Added a unit test, and CI passes.
2. Correlation
``` …
```

Remove try-except to ensure trace_link stops on exception

---

src/trace_link/kineto_operator.py
tests/trace_link/test_kineto_operator.py

Add missing keyword in `is_cuda_launch_op`. Postprocessors could not identify kernel-launching CUDA runtime operators because `cudaLaunchCooperativeKernel` was not in the dictionary of `is_cuda_launch_op`.
1. Updated unit tests, and CI passes
2. Correlation
```
$ pip install .                                             
git log
Requirement already satisfied: networkx in …
```

Add missing keyword in is_cuda_launch_op

---

src/trace_link/kineto_operator.py
src/trace_link/trace_linker.py
tests/trace_link/test_kineto_operator.py
tests/trace_link/test_trace_linker.py

- Renamed is_cuda_launch_op to is_kernel_launch_op.
- Added new methods to KinetoOperator: is_cuda_runtime_op, is_cuda_driver_op, and is_ac2g_op.
- Added unit tests for new and existing KinetoOperator methods.
- Updated TraceLinker to use the new is_kernel_launch_op method.
- Refactored code to improve quality and enhance test coverage.
This PR relies on the following PRs. These PRs below should be merged first.
* https://github.com/mlcommons/chakra/pull/122
* https://github.com/mlcommons/chakra/pull/123
* https://github.com/mlcommons/chakra/pull/124
* https://github.com/mlcommons/chakra/pull/125
* https://github.com/mlcommons/chakra/pull/126
```
$ pip install .                                                              
Installing build dependencies …
```

Refactor KinetoOperator and TraceLinker for code quality and test coverage

---

USER_GUIDE.md
src/trace_link/chakra_device_trace_loader.py
src/trace_link/chakra_host_trace_loader.py
src/trace_link/kineto_operator.py
src/trace_link/trace_link.py
src/trace_link/trace_linker.py
tests/trace_link/test_chakra_device_trace_loader.py
tests/trace_link/test_chakra_host_trace_loader.py
tests/trace_link/test_kineto_operator.py
tests/trace_link/test_trace_linker.py

Refactor trace_link for better maintainability and readability
1. CI passes.
2. Ran correlation
```
$ pip install .              
Requirement already satisfied: …
```

Refactor trace_link for better maintainability and readability

---

src/converter/converter.py
src/trace_link/trace_link.py
src/trace_link/trace_linker.py

Enhance logging messages for improved user experience
```
$ chakra_trace_link \
--chakra-host-trace /Users/theo/Downloads/et_0.json\
--chakra-device-trace /Users/theo/Downloads/kineto_0.json\
--output-file ~/megatron_0.json
[2024-07-23 12:04:09,946] trace_link.py:48 [INFO]: Linking process successful. Output file is available at /Users/theo/megatron_0.json.
[2024-07-23 12:04:09,946] trace_link.py:49 [INFO]: Please run the chakra_converter for further postprocessing.
$ chakra_converter PyTorch --input ~/megatron_0.json --output megatron_0.chakra
INFO [07/23/2024 12:09:21 PM] Conversion successful. Output file is available at megatron_0.chakra.
```

Enhance logging messages for improved user experience

---

.github/workflows/end_to_end_tests.yml
.github/workflows/python_tests.yml
USER_GUIDE.md
src/trace_link/chakra_device_trace_loader.py
src/trace_link/chakra_host_trace_loader.py
src/trace_link/kineto_operator.py
src/trace_link/trace_linker.py
tests/trace_link/test_chakra_host_trace_loader.py
tests/trace_link/test_trace_linker.py

Update PARAM import paths to reflect the latest main branch structure
```
$ pip install . 
Requirement already satisfied: pyparsing>=3 in …
```

Update PARAM import paths to reflect the latest main branch structure

---

src/converter/pytorch_converter.py
src/converter/pytorch_node.py
src/feeder/et_feeder_node.cpp
src/feeder/et_feeder_node.h
src/trace_link/kineto_operator.py
src/trace_link/trace_linker.py
tests/trace_link/test_trace_linker.py

Encoding communicator groups in Chakra traces is essential for accurately simulating collective communication when multiple communicator groups are present. With the latest PyTorch version, you can collect communicator groups in Chakra host traces (PyTorch execution traces) and Chakra device traces (Kineto traces). In Chakra host traces, you will find a process_group:init operator that presents the available communicator groups in the run. Moreover, whenever there is a collective communication operator, you can find essential fields in its attributes to correlate the collective operator with a communicator group. You can use the pg_name field for correlation. Additionally, Chakra device traces now include communicator group information in ncclDevKernel_* operators.
Below is an example …

Encode communicator groups in Chakra traces 

---

.github/workflows/end_to_end_tests.yml
.github/workflows/python_tests.yml
USER_GUIDE.md
src/converter/pytorch_converter.py
src/converter/pytorch_node.py
src/trace_link/chakra_device_trace_loader.py
src/trace_link/kineto_operator.py
src/trace_link/trace_link.py
src/trace_link/trace_linker.py
tests/trace_link/test_kineto_operator.py
tests/trace_link/test_trace_linker.py

* This PR relies on https://github.com/mlcommons/chakra/pull/119. It can be merged after https://github.com/mlcommons/chakra/pull/119 is merged.
This PR introduces dependencies from GPU operators to CPU operators using the critical path analysis in HolisticTraceAnalysis (HTA). In the simulation flow of Chakra, postprocessors like the trace linker and the converter are required. They are responsible for merging Chakra host traces with Chakra device traces and encoding dependencies. Currently, the dependencies encoded by the postprocessors are limited to CPU operators to GPU operators. However, there can be dependencies from GPU operators to CPU operators if a CPU operator has a dependency on a GPU operator. To identify such dependencies, this PR utilizes the critical path analysis of HTA. …

Support GPU-to-CPU synchronization dependency with HolisticTraceAnalysis

---

src/feeder/et_feeder_node.cpp
src/feeder/et_feeder_node.h

This PR updates ETFeeder to have getter functions of I/O attributes.
The I/O attributes include value/shape/type for the node.
Node that this feature is also required in other code in Feeder ( json_node.cpp  json_node.h  wrapper_node.cpp  wrapper_node.h) which can be done after we decide details of JSON format. 
This is tested with ASTRA-Sim as shown in below. 
```
void Workload::initialize_process_group(std::shared_ptr<Chakra::ETFeederNode> node) {
std::string pg_info = node->get_inputs_values();
if (pg_info.empty()) {
std::cerr << "Process Group Information is not encoded" << std::endl;
return;
}
....
}
```

Implement getter functions for ETFeeder

---

src/converter/pytorch_node.py

The PyTorch >2.5.0 appears to require support for schema version `1.1.1-chakra.0.0.4`.
The PR updates Chakra to include the most recent schema version in its supported list.
I tested the fixes using Mixtral 8x3B traces collected with the NeMo framework (NVIDIA).
[traces_device_0.zip](https://github.com/user-attachments/files/17368215/traces_device_0.zip)

Support newer PyTorch schema

---

src/trace_link/kineto_operator.py

Added Kernel Op names from HIP such as hipLaunchKernel, hipMemCpy, etc so that Chakra can work with AMD Traces.
In order to run the chakra trace linker on AMD devices, a similar PR must be made to HTA too, since the critical path analyzer from HTA is used in the chakra_trace_link function. A PR is posted to HTA (https://github.com/facebookresearch/HolisticTraceAnalysis/pull/225) and updated here soon. In the meantime, this patch can be used in the hta source directory as shown in the PR discussion to enable AMD GPUs.
In the Chakra Trace Linker, the is_kernel_launch_op() checks if a given op is a kernel launch op by comparing the op name against a set of cuda specific launch kernel names. In order for Chakra to work with AMD Kineto Traces, this has been updated to include the corresponding …

Added Kernel Launch Op names for AMD GPUs

---

src/converter/pytorch_converter.py
src/converter/pytorch_node.py
src/trace_link/trace_linker.py
tests/converter/test_pytorch_converter.py
tests/trace_link/test_trace_linker.py

This PR addresses multiple issues in the Chakra converter:
Chakra incorrectly distinguishes between point-to-point and collective communication. In NCCL, all-to-all is implemented as point-to-point communication, but Chakra's current logic treats these as distinct, leading to an incorrect type for `PyTorchNode`. More details on NCCL point-to-point can be found [here](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/p2p.html).
There was a mismatch in logging levels: sync dependencies log via `logging.info`, while other dependencies use `logging.debug`. This PR resolves the inconsistency by standardizing the logging approach.
HTA returns false positives for sync dependencies, leading to invalid `later op -> earlier op` dependencies. This causes Chakra to fail in certain …

Fix Chakra Errors

---

src/trace_link/trace_linker.py

some overlapping collectives occur because the timestamp of the GPU operation is overwritten with the timestamp of the runtime operation.
I dumped some relevant info from the device trace and from the resulting linked trace, where not only an overlap is noticeable, but also a mismatch between the starting/ending timestamps:
Kineto:
start:23:25:28.743436 duration:8932.93 end:23:25:28.752369 overlapped:False ncclDevKernel_AllReduce_Sum_f32_RING_LL
start:23:25:28.755013 duration:31272.55 end:23:25:28.786285 overlapped:False ncclDevKernel_AllReduce_Sum_f32_RING_LL
start:23:25:28.786286 duration:22644.126 end:23:25:28.808930 overlapped:False ncclDevKernel_AllReduce_Sum_f32_RING_LL
start:23:25:28.809750 duration:42481.079 end:23:25:28.852232 overlapped:False …

do not overwrite gpu op timestamp with runtime op timestamp

---

src/feeder/et_feeder_node.cpp

It was noticed that the debug and realease build were incoherent in terms of execution flow. The reason was narrowed down to num_ops_ being uninitialized, which triggered the astra-sim to take a different branch here:
https://github.com/astra-sim/astra-sim/blob/tutorial-hoti2024/astra-sim/workload/Workload.cc#L126
Run gcc sanitizer and check if the value is initialized.

Default num_ops_ to 0
